Fixes and general cleanup across the project
DragonBuild/dragon pull request #111
Opened 2022-08-06 15:45 UTC by L1ghtmann

Changes
---
- Added two more items created when dragon is installed via the dev script to the gitignore
- Updated krit* -> cynder
- Created and used new bash variables for dragon's primary directories:
  - $DRAGON_DIR=.dragon
  - $DRAGON_ROOT_DIR=$HOME/$DRAGON_DIR
  - $DRAGON_DATA_DIR=$PWD/$DRAGON_DIR (when $PWD != $HOME)
- Updated all bash scripts to use double-bracket syntax and write out one liners 
- Fixed a handful of previously-broken dragon options (e.g., remote, checkra1n, send, norm, etc)
- Fixed typos in a handful of comments
- Simplified some of the commands in the bash scripts
- Made common color echo functions to avoid code duplication
- Added missing shebangs and yml headers
- Removed an old DragonPrefs reference 
- Updated test repo links (5/8 fail on Linux due to one reason or another. If you could run the suite to confirm all work, that'd be great!)
- Will now properly determine max job number for ninja
- Updated prerun_checks to have a *complete* dependency check and resolution mech (tested on all platforms but MacOS -- guessed on the deps here please confirm)
- Used new $DRAGON* vars in the wizard
- Cleaned up python file imports
- A handful of smaller things I'm probably forgetting 

Got COVID recently and had some time to give dragon some love. Apologies for all the prs. And thanks again for this awesome project!

2022-08-07 14:00 UTC, cxnder requested changes

2022-08-07 14:00 UTC, cxnder commented on bin/dragon
> +        rs | respring )         python3 -m dragon.device run sbreload
Revert this line and everything else is good to go.

2022-08-07 14:00 UTC, cxnder commented on bin/dragon
> +        rs | respring )         python3 -m dragon.device run sbreload
hmu on discord for an explanation if needed.

2022-08-07 14:01 UTC, cxnder commented
Also, thank you sososososo much for this PR, this is amazing 😊 😊 😊 😊

2022-08-14 23:55 UTC, L1ghtmann commented
@cxnder Made a handful of minor changes since you last reviewed. Would you mind doing another once over if you're thinking of merging? Thanks!

2022-09-17 19:57 UTC, L1ghtmann commented
@MrGcGamer graciously gave this a spin and confirmed it's working as intended. 

If there's nothing else that you'd like changed @cxnder, this should be good to go.

2023-01-03 23:21 UTC, cxnder commented
Holy fuck, thanks

2023-01-03 23:22 UTC, merged